try{
    console.log(a);
    console.log("this stament wont gets executed");
}
catch(error){
    console.log("we got an error" +error);
}